# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('puerto', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
