# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rada', '0002_auto_20170728_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
